### ISSUE TITLE
Export the class as default export

### ISSUE THREAD

**Issue by pradel** [pradel/graphql-rules#1]
For little projects maybe create an export like that ` import { singleton } from 'graphql-rules' `

**Comment by giautm** [comment]
Default export currently is singleton. Because node require is cached and init only once.

```
import yourSingleton from 'graphql-rules'
```

**Comment by pradel** [comment]
Yeah I just want to change the current behavior.
`import GraphqlRules, { singleton }  from 'graphql-rule';`
The class will be the default export and the singleton a named export.
